
package au.com.woolworths.portal.pplanner.create;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeatPlannerServiceEndPoint", targetNamespace = "http://service.replenishment.woolworths.com.au/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeatPlannerServiceEndPoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<au.com.woolworths.portal.pplanner.create.ResponseData>
     * @throws ServiceFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlanInfo", targetNamespace = "http://service.replenishment.woolworths.com.au/", className = "au.com.woolworths.portal.pplanner.create.GetPlanInfo")
    @ResponseWrapper(localName = "getPlanInfoResponse", targetNamespace = "http://service.replenishment.woolworths.com.au/", className = "au.com.woolworths.portal.pplanner.create.GetPlanInfoResponse")
    @Action(input = "http://service.replenishment.woolworths.com.au/MeatPlannerServiceEndPoint/getPlanInfoRequest", output = "http://service.replenishment.woolworths.com.au/MeatPlannerServiceEndPoint/getPlanInfoResponse", fault = {
        @FaultAction(className = ServiceFault_Exception.class, value = "http://service.replenishment.woolworths.com.au/MeatPlannerServiceEndPoint/getPlanInfo/Fault/ServiceFault")
    })
    public List<ResponseData> getPlanInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        List<RequestData> arg0)
        throws ServiceFault_Exception
    ;

}
