
package au.com.woolworths.portal.pplanner.create;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.beans.factory.annotation.Value;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeatPlannerServiceImpl", targetNamespace = "http://service.replenishment.woolworths.com.au/")
public class MeatPlannerServiceImpl
    extends Service
{
	

//    private final static URL MEATPLANNERSERVICEIMPL_WSDL_LOCATION;
//    private final static WebServiceException MEATPLANNERSERVICEIMPL_EXCEPTION;
    private final static QName MEATPLANNERSERVICEIMPL_QNAME = new QName("http://service.replenishment.woolworths.com.au/", "MeatPlannerServiceImpl");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("file:/U:/Desktop/kishore/3/MeatPlanner.wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        } 
//        MEATPLANNERSERVICEIMPL_WSDL_LOCATION = url;
//        MEATPLANNERSERVICEIMPL_EXCEPTION = e;
//    }

//    public MeatPlannerServiceImpl() throws MalformedURLException {
//        super(MEATPLANNERSERVICEIMPL_WSDL_LOCATION, MEATPLANNERSERVICEIMPL_QNAME);
//    }

//    public MeatPlannerServiceImpl(WebServiceFeature... features) {
//        super(__getWsdlLocation(), MEATPLANNERSERVICEIMPL_QNAME, features);
//    }

    public MeatPlannerServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, MEATPLANNERSERVICEIMPL_QNAME);
    }

    public MeatPlannerServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEATPLANNERSERVICEIMPL_QNAME, features);
    }

    public MeatPlannerServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeatPlannerServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeatPlannerServiceEndPoint
     */
    @WebEndpoint(name = "MeatPlannerServiceEndPointPort")
    public MeatPlannerServiceEndPoint getMeatPlannerServiceEndPointPort() {
        return super.getPort(new QName("http://service.replenishment.woolworths.com.au/", "MeatPlannerServiceEndPointPort"), MeatPlannerServiceEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeatPlannerServiceEndPoint
     */
    @WebEndpoint(name = "MeatPlannerServiceEndPointPort")
    public MeatPlannerServiceEndPoint getMeatPlannerServiceEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.replenishment.woolworths.com.au/", "MeatPlannerServiceEndPointPort"), MeatPlannerServiceEndPoint.class, features);
    }

//    private static URL __getWsdlLocation() {
//        if (MEATPLANNERSERVICEIMPL_EXCEPTION!= null) {
//            throw MEATPLANNERSERVICEIMPL_EXCEPTION;
//        }
//        return MEATPLANNERSERVICEIMPL_WSDL_LOCATION;
//    }

}
